[package]
name = "omnipath"
description = "Path utlity library"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["windows", "absolute"]
categories = ["filesystem"]
repository = "https://github.com/ChrisDenton/omnipath"

[features]
default = ["std"]
std = []
